spring:
  application:
    name: backend_levelup

  datasource:
    url: jdbc:oracle:thin:@jokuhv2vm15s47bc_high?TNS_ADMIN=C:/Users/ragal/IdeaProjects/backend_levelup/oracle/wallet
    username: levelup_user
    password: +a1{3MFG*E2789G
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect



application:
  security:
    jwt:
      secret-key: 16d797f66e19a8589e06a094f1e0f74886630f46645f9d578ff6f97cf611ab0a
